AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Description: >
  Automatically create snapshots from all Lightsail Virtual Private Servers
  each day and prune snapshots after a retention period.

Parameters:
  RetentionDays:
    Type: String
    Description: The number of days to retain snapshots.
    Default: 30
  Schedule:
    Type: String
    Description: Event schedule of create snapshot.
    Default: rate(1 day)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      RetentionDays:
        default: Retention Days
      Schedule:
        default: Event Schedule

Resources:
  AutoSnapshot:
    Type: AWS::Serverless::Function
    Properties:
      Description: >
        Automatically create snapshots from all Lightsail Virtual Private
        Servers and prune snapshots after a retention period.
      CodeUri: ./lambda
      Runtime: python3.9
      Timeout: 60
      Handler: index.handler
      Environment:
        Variables:
          RETENTION_DAYS: !Ref RetentionDays
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: !Ref Schedule
      Policies:
          Statement:
            - Resource: "*"
              Effect: Allow
              Action:
                - lightsail:GetInstances
                - lightsail:GetInstanceSnapshots
                - lightsail:CreateInstanceSnapshot
                - lightsail:DeleteInstanceSnapshot
